/* GENERATED by gen-forwarders.sh -- do not edit. */
#ifndef UUYC_VDSHIM_FORWARDERS_H
#define UUYC_VDSHIM_FORWARDERS_H

/* One writable slot per trampoline. Filled at process attach from the
 * real Wine d3d11.dll; left pointing at a safe stub if it is absent.
 * Declared extern here so several translation units can include this. */
extern void *uuyc_slot_D3D11CoreCreateLayeredDevice;
extern void *uuyc_slot_D3D11CoreGetLayeredDeviceSize;
extern void *uuyc_slot_D3D11CoreRegisterLayers;
extern void *uuyc_slot_D3D11On12CreateDevice;
extern void *uuyc_slot_D3DKMTCheckVidPnExclusiveOwnership;
extern void *uuyc_slot_D3DKMTCloseAdapter;
extern void *uuyc_slot_D3DKMTCreateAllocation;
extern void *uuyc_slot_D3DKMTCreateContext;
extern void *uuyc_slot_D3DKMTCreateDevice;
extern void *uuyc_slot_D3DKMTCreateSynchronizationObject;
extern void *uuyc_slot_D3DKMTDestroyAllocation;
extern void *uuyc_slot_D3DKMTDestroyContext;
extern void *uuyc_slot_D3DKMTDestroyDevice;
extern void *uuyc_slot_D3DKMTDestroySynchronizationObject;
extern void *uuyc_slot_D3DKMTEscape;
extern void *uuyc_slot_D3DKMTGetContextSchedulingPriority;
extern void *uuyc_slot_D3DKMTGetDeviceState;
extern void *uuyc_slot_D3DKMTGetDisplayModeList;
extern void *uuyc_slot_D3DKMTGetMultisampleMethodList;
extern void *uuyc_slot_D3DKMTGetRuntimeData;
extern void *uuyc_slot_D3DKMTGetSharedPrimaryHandle;
extern void *uuyc_slot_D3DKMTLock;
extern void *uuyc_slot_D3DKMTOpenAdapterFromGdiDisplayName;
extern void *uuyc_slot_D3DKMTOpenAdapterFromHdc;
extern void *uuyc_slot_D3DKMTOpenResource;
extern void *uuyc_slot_D3DKMTPresent;
extern void *uuyc_slot_D3DKMTQueryAdapterInfo;
extern void *uuyc_slot_D3DKMTQueryAllocationResidency;
extern void *uuyc_slot_D3DKMTQueryResourceInfo;
extern void *uuyc_slot_D3DKMTRender;
extern void *uuyc_slot_D3DKMTSetAllocationPriority;
extern void *uuyc_slot_D3DKMTSetContextSchedulingPriority;
extern void *uuyc_slot_D3DKMTSetDisplayMode;
extern void *uuyc_slot_D3DKMTSetDisplayPrivateDriverFormat;
extern void *uuyc_slot_D3DKMTSetGammaRamp;
extern void *uuyc_slot_D3DKMTSetVidPnSourceOwner;
extern void *uuyc_slot_D3DKMTSignalSynchronizationObject;
extern void *uuyc_slot_D3DKMTUnlock;
extern void *uuyc_slot_D3DKMTWaitForSynchronizationObject;
extern void *uuyc_slot_D3DKMTWaitForVerticalBlankEvent;
extern void *uuyc_slot_OpenAdapter10;
extern void *uuyc_slot_OpenAdapter10_2;

/* Filled in by the caller-provided resolver. */
typedef void *(*uuyc_resolve_fn)(const char *name);
void uuyc_forwarders_init(uuyc_resolve_fn resolve, void *fallback);

#endif
