#!/usr/bin/bash
# gen-forwarders.sh -- generate the pass-through exports the shim is missing.
#
# Why this is needed
# ------------------
# The shim is deployed AS d3d11.dll. A PE that imports a symbol this DLL does not
# export fails to load, and in-process that looks like an instant crash of the
# whole application -- which is exactly what "installing the shim makes the
# client crash" turned out to be.
#
# The shim implements only the three device-creation entry points it needs:
#
#     D3D11CreateDevice, D3D11CreateDeviceAndSwapChain, D3D11CoreCreateDevice
#
# Wine's d3d11.dll exports 45. The other 42 (the D3DKMT* family, OpenAdapter10,
# D3D11On12CreateDevice, the layer helpers) are never called by this client, but
# their presence in the export table is mandatory for anything that imports them.
#
# So: emit one tiny assembly trampoline per missing name. A trampoline is a bare
# `jmp *slot(%rip)`, which is a tail call -- it preserves every register and the
# stack exactly, so the real function sees the original arguments unchanged.
# The slot is filled from the real Wine d3d11.dll at process attach.
#
# Regenerate whenever the host Wine changes its d3d11 exports.
#
# Usage:
#     bash gen-forwarders.sh [/path/to/wine/d3d11.dll]
#
# SPDX-License-Identifier: 0BSD
set -uo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
wine_d3d11=${1:-/usr/lib/wine/x86_64-windows/d3d11.dll}
out_prefix=${2:-$here/uuyc-vdshim-forwarders}
shift 2 2>/dev/null || true

[[ -r $wine_d3d11 ]] || { printf 'cannot read %s\n' "$wine_d3d11" >&2; exit 1; }

PYTHON=${PYTHON:-python3}
if ! "$PYTHON" -c 'import pefile' 2>/dev/null; then
    for cand in /home/daoxiang/ds-workplace/work/venv/bin/python3 "$(command -v python3)"; do
        [[ -x $cand ]] || continue
        if "$cand" -c 'import pefile' 2>/dev/null; then PYTHON=$cand; break; fi
    done
fi

"$PYTHON" - "$wine_d3d11" "$out_prefix" "$@" <<'PY'
import sys, re, os
wine_dll, prefix = sys.argv[1], sys.argv[2]

# Names the shim implements itself. Defaults to the d3d11 set; callers that
# shim another DLL pass their own list as extra arguments.
implemented = set(sys.argv[3:]) or {"D3D11CreateDevice", "D3D11CreateDeviceAndSwapChain", "D3D11CoreCreateDevice"}

# Prefer pefile; fall back to parsing objdump when it is unavailable.
names = None
try:
    import pefile
    pe = pefile.PE(wine_dll, fast_load=True)
    pe.parse_data_directories(
        directories=[pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_EXPORT']])
    names = {e.name.decode() for e in pe.DIRECTORY_ENTRY_EXPORT.symbols if e.name}
except Exception:
    names = None

if not names:
    import subprocess
    txt = subprocess.run(["objdump", "-p", wine_dll], capture_output=True, text=True).stdout
    block = txt.split("[Ordinal/Name Pointer] Table", 1)
    if len(block) != 2:
        sys.exit("could not parse the export table of " + wine_dll)
    names = set()
    for line in block[1].splitlines():
        # format: "\t[   0] +base[   1]  0000 D3D11CreateDevice"
        parts = line.split()
        if parts and parts[-1][:1].isalpha() and re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", parts[-1]):
            names.add(parts[-1])

missing = sorted(names - implemented)
if not missing:
    sys.exit("nothing to forward: the shim already covers every export")

# --- assembly trampolines -------------------------------------------------
with open(prefix + ".S", "w") as f:
    f.write("/* GENERATED by gen-forwarders.sh -- do not edit. */\n")
    f.write("/* One tail-jump per export the shim forwards to the real Wine d3d11.dll. */\n\n")
    f.write("    .text\n\n")
    for n in missing:
        f.write(f"    .globl {n}\n")
        f.write(f"    .def {n}; .scl 2; .type 32; .endef\n")
        f.write(f"{n}:\n")
        f.write(f"    jmp *uuyc_slot_{n}(%rip)\n\n")

# --- .def listing every export -------------------------------------------
with open(prefix + ".def", "w") as f:
    f.write("; GENERATED by gen-forwarders.sh -- do not edit.\n")
    f.write("EXPORTS\n")
    for n in sorted(implemented | set(missing)):
        f.write(f"    {n}\n")

# --- C fragment: the slots plus a resolver --------------------------------
with open(prefix + ".h", "w") as f:
    f.write("/* GENERATED by gen-forwarders.sh -- do not edit. */\n")
    guard = os.path.basename(prefix).replace("-", "_").replace(".", "_").upper() + "_H"
    f.write("#ifndef %s\n#define %s\n\n" % (guard, guard))
    f.write("/* One writable slot per trampoline. Filled at process attach from the\n")
    f.write(" * real Wine d3d11.dll; left pointing at a safe stub if it is absent.\n")
    f.write(" * Declared extern here so several translation units can include this. */\n")
    for n in missing:
        f.write(f"extern void *uuyc_slot_{n};\n")
    f.write("\n/* Filled in by the caller-provided resolver. */\n")
    f.write("typedef void *(*uuyc_resolve_fn)(const char *name);\n")
    f.write("void uuyc_forwarders_init(uuyc_resolve_fn resolve, void *fallback);\n\n")
    f.write("#endif\n")

with open(prefix + ".c", "w") as f:
    f.write("/* GENERATED by gen-forwarders.sh -- do not edit. */\n")
    base = os.path.basename(prefix)
    guard = base.replace("-", "_").replace(".", "_").upper() + "_H"
    f.write('#include "%s.h"\n\n' % base)
    f.write("/* The single definition of every slot. */\n")
    for n in missing:
        f.write(f"void *uuyc_slot_{n};\n")
    f.write("\nvoid uuyc_forwarders_init(uuyc_resolve_fn resolve, void *fallback)\n{\n")
    f.write("    void *p;\n\n")
    for n in missing:
        f.write(f'    p = resolve("{n}");\n')
        f.write(f'    uuyc_slot_{n} = p ? p : fallback;\n')
    f.write("}\n")

print(f"generated {len(missing)} forwarders ({len(names)} exports in {wine_dll})")
PY
